### PR TITLE
Add TaskInfo message

### PR DESCRIPTION
**Pull request by mpowelson**
This adds the TaskInfo message. With the utilities together with toFile and fromFile (tesseract_rosutils), this should allow you to save the inputs and outputs of a Task to a file and replay them later.

Proposed next steps
- [ ] Make a utility that saves an entire TaskInfoContainer to a directory. Optionally zip it into a single file
- [ ] Create a very simple RVIZ display to load that file and visualize these TaskInfos

### CODE REVIEW

**Comment by mpowelson** [comment]
@Levi-Armstrong This is ready for review

**Comment by mpowelson** [comment]
Probably easiest to look at each commit on this one.

**Comment by mpowelson** [comment]
@Levi-Armstrong Finally made CI happy.

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by Levi-Armstrong** [comment]
Looks good.

**Comment by mpowelson** [comment]
Note that this is a breaking change as it updates the TesseractState msg to be called EnvironmentState since the Tesseract object has been removed.

**Pull request merged**
