### PR TITLE
Add Tesseract.msg and conversion utils

### PR DESCRIPTION
**Pull request by mpowelson**

### CODE REVIEW

**Review by Levi-Armstrong — APPROVED** [review]
Looks Good!

**Comment by Levi-Armstrong** [comment]
@mpowelson One thing, the request currently has the remapping do we want to include that in the archive message?

**Comment by mpowelson** [comment]
I probably would for completeness. I do wonder if this should be a separate message. We could just have both a tesseract state and a tesseract in the planning request and some way to tell which one we are supposed to use.

**Comment by Levi-Armstrong** [comment]
Is this good to merge or were you going to add the profile remapping?

**Comment by mpowelson** [comment]
I already had the profile remapping. I thought you were asking if I wanted to remove it. Or am I misunderstanding?

**Comment by Levi-Armstrong** [comment]
Oh, my mistake. I thought it was missing.

**Comment by Levi-Armstrong** [comment]
Go ahead and merge if your good with it.

**Comment by mpowelson** [comment]
It's not super full featured, but I think we can improve it in future PRs.

**Pull request merged**
