### PR TITLE
Correct Header for SRDF Model

### PR DESCRIPTION
**Pull request by mpowelson**
Will be necessary when @Levi-Armstrong merges his improvements to the SRDF into Tesseract ([PR 292](https://github.com/ros-industrial-consortium/tesseract/pull/292)

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
SRDF does not describe models, but additional metadata. Is that the correct name for the header?

**Comment by Levi-Armstrong** [comment]
> SRDF does not describe models, but additional metadata. Is that the correct name for the header?

Probably not. Any recommendations? We could rename it to EnvMetadata or SceneMetadata.

**Comment by Levi-Armstrong** [comment]
If you enable the tests does it still fail?

**Comment by mpowelson** [comment]
Yes. Its possible/probable that its an intermittent thing. You'll notice I didn't do anything to fix the pick and place example. It just happened to work this time.

**Pull request merged**
