### PR TITLE
Add Archive Viewer

### PR DESCRIPTION
**Pull request by mpowelson**
Depends on #41 and #42. Allows you to view a directory of planning response archives for debugging. 

It is a bit simple at the moment, but it does work.

### CODE REVIEW

**Comment by mpowelson** [comment]
Pushed minor change making publisher latching

**Comment by mpowelson** [comment]
Rebased. This one should be ready for review as well. It is not very full featured, but it works as a starting point for modification to debug your specific situation.

**Comment by Levi-Armstrong** [comment]
@mpowelson It looks good, could you rebase and then once CI passes you are good to merge.

**Comment by Levi-Armstrong** [comment]
If you rebase this now the CI should pass.

**Comment by Levi-Armstrong** [comment]
Wait, if you rebase on my open PR it should pass.

**Comment by mpowelson** [comment]
@Levi-Armstrong Is this still ok to merge? It's been a while, but it is passing now.

**Review by Levi-Armstrong — APPROVED** [review]

**Pull request merged**
